//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.17 at 10:40:22 AM MSK 
//


package com.epam.spring.core.soap.bean.user.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.epam.spring.core.soap.endpoints.bean.user.GetAllUsersRequest;
import com.epam.spring.core.soap.endpoints.bean.user.GetAllUsersResponse;
import com.epam.spring.core.soap.endpoints.bean.user.GetUserByEmailRequest;
import com.epam.spring.core.soap.endpoints.bean.user.GetUserByIdRequest;
import com.epam.spring.core.soap.endpoints.bean.user.RemoveUserRequest;
import com.epam.spring.core.soap.endpoints.bean.user.SaveUserRequest;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAllUsersRequest_QNAME = new QName("http://spring-course.com/schemas", "GetAllUsersRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllUsersResponse }
     * 
     */
    public GetAllUsersResponse createGetAllUsersResponse() {
        return new GetAllUsersResponse();
    }

    /**
     * Create an instance of {@link SaveUserRequest }
     * 
     */
    public SaveUserRequest createSaveUserRequest() {
        return new SaveUserRequest();
    }

    /**
     * Create an instance of {@link GetUserByEmailRequest }
     * 
     */
    public GetUserByEmailRequest createGetUserByEmailRequest() {
        return new GetUserByEmailRequest();
    }

    /**
     * Create an instance of {@link GetUserByIdRequest }
     * 
     */
    public GetUserByIdRequest createGetUserByIdRequest() {
        return new GetUserByIdRequest();
    }

    /**
     * Create an instance of {@link RemoveUserRequest }
     * 
     */
    public RemoveUserRequest createRemoveUserRequest() {
        return new RemoveUserRequest();
    }
    
    /**
     * Create an instance of {@link GetAllUsersRequest }
     * 
     */
    public GetAllUsersRequest createGetAllUsersRequest() {
        return new GetAllUsersRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://spring-course.com/schemas", name = "GetAllUsersRequest")
    public JAXBElement<Object> createGetAllUsersRequest(Object value) {
        return new JAXBElement<Object>(_GetAllUsersRequest_QNAME, Object.class, null, value);
    }

}
